### ISSUE TITLE
error TS2511: Cannot create an instance of an abstract class.

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#2151]
After upgrade TypeScript from 3.9 to 4.2, we got the following error message when running `tsc`

```sh
> tsc --noEmit

src/puppet-manager.ts:105:24 - error TS2511: Cannot create an instance of an abstract class.

105       puppetInstance = new MyPuppet(options.puppetOptions)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

VSCode shows the `MyPuppet` is `const MyPuppet: new (options?: PuppetOptions | undefined) => Puppet`

After downgrade to TypeScript 3.9, everything back to normal.

To be investigated.

**Comment by huan** [comment]
## Update

https://github.com/wechaty/wechaty/blob/c6238af2a8b491d927d206ad2e3d1962227840ba/src/puppet-manager.ts#L101-L107

**Comment by kevinmora47** [comment]
So when we instance a new class, we should define the type of it?

**Comment by huan** [comment]
No, we shouldn't.

This issue is only related to the internal design of the Wechaty.

When using Wechaty, we can use `new Wechaty()` to instance it.

You can learn how to getting started from https://github.com/wechaty/wechaty-getting-started and our docs at https://wechaty.js.org/docs/getting-started/

**Comment by huan** [comment]
It seems that the TypeScript version 4.4.2 has resolved this problem.
