### ISSUE TITLE
Fail to Run at Linux

### ISSUE THREAD

**Issue by zzc-tongji** [wechaty/wechaty#2005]
### Description

- Fail to run at Linux.

### Environment

- Wechaty 0.40.10
- wechaty-puppet-puppeteer (default)
- Node.js v12.16.2
- Linux / Ubuntu 20.04 LTS (server version without GUI)

### Representation

- Use any wechaty project on Windows.
- Execute `npm install  && npm start`.

### Log

(I try to redirect all logs to file **but it still outputs some logs to console**. Maybe here is another bug.)

#### Run at the First Time

Log of Console

``` text
Error: Cannot find module 'wechaty-puppet-puppeteer'
Require stack:
- /root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/puppet-manager.js
- /root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/wechaty.js
- /root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/index.js
- /root/wechat-assistant/wechaty/src/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /root/wechat-assistant/wechaty/node_modules/wechaty/src/puppet-manager.ts:120:26 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/puppet-manager.js',
    '/root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/wechaty.js',
    '/root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/index.js',
    '/root/wechat-assistant/wechaty/src/main.js'
  ]
}
13:09:14 ERR Wechaty start() exception: Cannot find module 'wechaty-puppet-puppeteer'
Require stack:
- /root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/puppet-manager.js
- /root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/wechaty.js
- /root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/index.js
- /root/wechat-assistant/wechaty/src/main.js
13:09:14 WARN Wechaty stop() puppet.stop() exception: Cannot read property 'stop' of undefined
```

Log of File

``` text
yarn run v1.22.4
$ cd runtime/ && babel-node ../src/main.js
13:08:53 INFO PuppetManager install(wechaty-puppet-puppeteer@^0.21.2) please wait ...
npm: npm
npm:
npm: WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

npm: npm
npm:  WARN lifecycle The node binary used for scripts is /tmp/yarn--1592312930566-0.8170432711800566/node but npm is using /root/.nvm/versions/node/v12.18.0/bin/node
itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

npm:
> puppeteer@2.1.1 install /root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/puppeteer
> node install.js


npm:

npm: Chromium downloaded to /root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-722234

npm: npm
npm:
npm: WARN
npm:  wechaty-puppet-puppeteer@0.21.2 requires a peer of wechaty-puppet@^0.21.12 but none is installed. You must install peer dependencies yourself.

npm: npm
npm:
npm: WARN
npm:  rx-queue@0.8.5 requires a peer of brolog@^1.4.9 but none is installed. You must install peer dependencies yourself.

npm:

npm: + wechaty-puppet-puppeteer@0.21.2
added 135 packages from 216 contributors and audited 11 packages in 20.059s

npm:
2 packages are looking for funding
  run `npm fund` for details


npm: found 0 vulnerabilities


13:09:14 INFO PuppetManager install(wechaty-puppet-puppeteer@^0.21.2) done
13:09:14 INFO wechaty::error Error: Cannot find module 'wechaty-puppet-puppeteer'
Require stack:
- /root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/puppet-manager.js
- /root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/wechaty.js
- /root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/index.js
- /root/wechat-assistant/wechaty/src/main.js
13:09:14 INFO wechaty::stop
Done in 24.40s.
```

#### Run

Log of Console

``` text
13:14:24 ERR PuppetPuppeteerBridge start() exception: Error: Failed to launch the browser process!
/root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

13:14:24 ERR PuppetPuppeteer initBridge() exception: Failed to launch the browser process!
/root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

13:14:24 ERR PuppetPuppeteer initBridge() this.bridge.stop() rejection: Error: no page
13:14:24 ERR PuppetPuppeteer start() exception: Error: Failed to launch the browser process!
/root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

13:14:24 ERR PuppetPuppeteer this.bridge.quit() exception: no page
Error: no page
    at Bridge.<anonymous> (/root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/src/bridge.ts:327:13)
    at Generator.next (<anonymous>)
    at /root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/bridge.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/bridge.js:23:12)
    at Bridge.stop (/root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/bridge.js:263:16)
    at PuppetPuppeteer.<anonymous> (/root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:287:25)
    at Generator.next (<anonymous>)
    at /root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:26:71
    at new Promise (<anonymous>)
    at __awaiter (/root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:22:12)
    at PuppetPuppeteer.stop (/root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:172:16)
    at PuppetPuppeteer.<anonymous> (/root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:202:18)
    at Generator.throw (<anonymous>)
    at rejected (/root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:24:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
13:14:24 ERR Wechaty start() exception: no page
13:14:24 WARN PuppetPuppeteer stop() is called on a OFF puppet. await ready(off) and return.
```

Log of File

``` text
yarn run v1.22.4
$ cd runtime/ && babel-node ../src/main.js
13:08:53 INFO PuppetManager install(wechaty-puppet-puppeteer@^0.21.2) please wait ...
npm: npm
npm:
npm: WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

npm: npm
npm:  WARN lifecycle The node binary used for scripts is /tmp/yarn--1592312930566-0.8170432711800566/node but npm is using /root/.nvm/versions/node/v12.18.0/bin/node
itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

npm:
> puppeteer@2.1.1 install /root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/puppeteer
> node install.js


npm:

npm: Chromium downloaded to /root/wechat-assistant/wechaty/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-722234

npm: npm
npm:
npm: WARN
npm:  wechaty-puppet-puppeteer@0.21.2 requires a peer of wechaty-puppet@^0.21.12 but none is installed. You must install peer dependencies yourself.

npm: npm
npm:
npm: WARN
npm:  rx-queue@0.8.5 requires a peer of brolog@^1.4.9 but none is installed. You must install peer dependencies yourself.

npm: + wechaty-puppet-puppeteer@0.21.2
npm:

added 135 packages from 216 contributors and audited 11 packages in 20.059s

npm:
2 packages are looking for funding
  run `npm fund` for details


npm: found 0 vulnerabilities


13:09:14 INFO PuppetManager install(wechaty-puppet-puppeteer@^0.21.2) done
13:09:14 INFO wechaty::error Error: Cannot find module 'wechaty-puppet-puppeteer'
Require stack:
- /root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/puppet-manager.js
- /root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/wechaty.js
- /root/wechat-assistant/wechaty/node_modules/wechaty/dist/src/index.js
- /root/wechat-assistant/wechaty/src/main.js
13:09:14 INFO wechaty::stop
Done in 24.40s.
```

**Comment by zzc-tongji** [comment]
### Solution

- https://github.com/wechaty/wechaty/issues/1152#issuecomment-403158301
- https://github.com/Chatie/wechaty/blob/cca528894af37483960eed8dd1d5a0803f4b106f/Dockerfile#L41-L51
- It works on Ubuntu 20.04 LTS.

**Comment by zzc-tongji** [comment]
File `pre-install.linux.sh`

``` sh
#!/bin/sh

if [ $(cat /etc/os-release | grep -ci "debian\|ubuntu") -gt 0 ]; then
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update && apt-get install -y --no-install-recommends google-chrome-unstable \
  && apt-get purge --auto-remove \
  && rm -rf /tmp/* /var/lib/apt/lists/* \
  && rm -rf /usr/bin/google-chrome* /opt/google/chrome-unstable
else
  echo "[Error] unsupported linux distribution"
  exit 1
fi
```

**Comment by huan** [comment]
@zzc-tongji Thank you for sharing the solution that solved your issue!

Would you like to add those tips to our README of wechaty-getting-started, so that it can help other developers in the future?

**Comment by zzc-tongji** [comment]
Fine.

**Comment by huan** [comment]
Close this issue due to no activities for more than 6 months.
